### ISSUE TITLE
v0.4 to-do list

### ISSUE THREAD

**Issue by asemposki** [bandframework/Taweret#109]
Task list for the updated Taweret package for inclusion into the new release of the bandframework. 

- [ ] Successfully test the Jupyter Book build by intentionally breaking it and seeing how the GitHub Actions respond.
- [ ] Add some more information into the Book that introduces it and guides the reader.
- [ ] Check each GitHub Action, and determine whether they are integrated into our current git workflow.
- [ ] Enable `dependabot` and test it.
- [ ] Determine how our deployment will look to PyPI, and deploy Taweret.
- [ ] Clean up the issues to stay up to date.

**Comment by jared321** [comment]
@jcyannotty  Alexandra and I are working on finalizing v1.1.0 for inclusion in the upcoming BAND v0.4 release.  At present, we intend to have Taweret use the `openbtmixing` binary wheels that you presently have in PyPI.  Once your post v0.4 changes are made, I would try to implement the new build system and distribution scheme.  Those two changes would then be a new release.  Is this acceptable for you?

There are two macOS/arm64 wheels available (v10.9 and 12.0).  If I remember correctly, they were uploaded because I was having issues on my machine, but that we never finalized those so that they might be "unofficial" wheels.  The Taweret GH actions do run on arm64 runners and are passing.  In the logs I see that they use `openbtmixing-1.0.1-py3-none-macosx_12_0_arm64.whl`.  However, that was built for my machine because the logs say that the OpenBT CLTs have the following dependencies
```
openbtcli:
	/Users/jared/local/OpenBT/lib/libsinglebinomial.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libsinglepoisson.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libpsbrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libambrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libsbrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libmbrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libbrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libtree.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libcrn.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libamxbrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/jared/local/OpenBT/lib/libmxbrt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/homebrew/opt/open-mpi/lib/libmpi.40.dylib (compatibility version 81.0.0, current version 81.3.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```
I don't presently understand how these are passing.  I'd guess that this was built such that the paths hardcoded to my installation at the time of building the wheel are a suggestion rather than a requirement.

@jcyannotty @asemposki  Should we pull these wheels down and note in the Taweret docs that binary wheels for macOS/arm64 should be made available soon?  Leave it as is?

**Comment by asemposki** [comment]
@jared321 Do we need `CleanPackage` or `91_SphinxClean` anymore? If not, we can delete those branches, since both have been PR'd into `main` and their history should be there now.

**Comment by asemposki** [comment]
@jared321 Also, how much more of this list should we expect to complete before we PR into `develop`? Do we want to wait on `dependabot` until after v0.4, given how it can be a good amount of work?

**Comment by jared321** [comment]
Branches deleted.  This included `91_RtdPublish`.

We can wait on dependabot if you want.  It looks like we should do all others.

**Comment by asemposki** [comment]
> @jcyannotty @asemposki Should we pull these wheels down and note in the Taweret docs that binary wheels for macOS/arm64 should be made available soon? Leave it as is?

I think we probably should pull down the wheels and note that they'll be available soon, or simply that we are refactoring things and it will be fixed soon, if they are hardcoded like that.

**Comment by asemposki** [comment]
(Finalized review checklist)
The following checklist is for Taweret team reviewers (@asemposki, @jared321) at the moment, but will be also copied into the PR draft so that it can be checked by the BAND v0.4 reviewers.

Functionality tests:
- [ ] (Taweret team reviewers ONLY) Follow instructions under [ArmDocs](https://github.com/jcyannotty/OpenBT/blob/ArmDocs/README.md) to build openBT command line tools for Mac. 
- [ ] Check the Taweret pypi package by downloading from there.

User interaction tests:
- [ ] Run one of the Jupyter notebooks found in the folder `Taweret/book/notebooks/LMM`. This may take a few hundred seconds depending on which one is chosen, due to the MCMC sampling call. This will test if `seaborn` and `ptemcee` are properly able to be installed, as they are no longer named directly as Taweret dependences.
- [ ] Go to the Jupyter Book [here](https://bandframework.github.io/Taweret/notebooks/Biv_BMM/Bivariate_Test.html) and test launching to Google Colab using the little rocket shaped button at the top of the notebook page, and see if this notebook will run there.

Documentation review:
- [ ] (Taweret team reviewers ONLY) Read the RTD pages [here](https://taweretdocs.readthedocs.io/en/latest/) and see if they are satisfactory and clear.

**Comment by asemposki** [comment]
Had to add a commented out line to pip install Taweret in the Colab runs of the notebooks. That seemed to do the trick for me.

**Comment by asemposki** [comment]
Re-checked the openBT list and it all works for me again!

**Comment by asemposki** [comment]
OK I'm good with all checks above. @jared321 You can run through them and see if they work for you before we finish up this release. :) I think now the last thing is the PyPi release. I will draft the release for Taweret, and draft the PR into `develop` once we're done with the PyPi checks/investigations.

**Comment by asemposki** [comment]
@jared321 Not sure what's up with the test for macOS version 12, it seems to have package version issues. Considering only one line, that is commented out, was added in the notebooks, this seems to be another problem.

**Comment by jared321** [comment]
> @jared321 Not sure what's up with the test for macOS version 12, it seems to have package version issues. Considering only one line, that is commented out, was added in the notebooks, this seems to be another problem.

I see the following error in that failed job
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
```
This is likely a security check to make sure that you have downloaded what you expected to download and not a nefarious package.  I have seen this once or twice before.  While it could be a real security issue, it might just also be a glitch that doesn't show up on subsequent runs.  Indeed, I see that that job is again passing on `main`.

**Comment by jared321** [comment]
Functionality tests:
- [ ] (Taweret team reviewers ONLY) Follow instructions under [ArmDocs](https://github.com/jcyannotty/OpenBT/blob/ArmDocs/README.md) to build openBT command line tools for Mac. 
- [ ] Check the Taweret pypi package by downloading from there.

User interaction tests:
- [ ] Run one of the Jupyter notebooks found in the folder `Taweret/book/notebooks/LMM`. This may take a few hundred seconds depending on which one is chosen, due to the MCMC sampling call. This will test if `seaborn` and `ptemcee` are properly able to be installed, as they are no longer named directly as Taweret dependences.
- [ ] Go to the Jupyter Book [here](https://bandframework.github.io/Taweret/notebooks/Biv_BMM/Bivariate_Test.html) and test launching to Google Colab using the little rocket shaped button at the top of the notebook page, and see if this notebook will run there.

Documentation review:
- [ ] (Taweret team reviewers ONLY) Read the RTD pages [here](https://taweretdocs.readthedocs.io/en/latest/) and see if they are satisfactory and clear.

**Comment by asemposki** [comment]
OK so I think the final thing to do is actually deploy to PyPI, which we should have done tomorrow morning, if I'm correct? Then I can open the PR tomorrow afternoon for others to test Taweret.

**Comment by asemposki** [comment]
OK everything looks good to go!
